=== BeignetBoyy/IOT-Regulateur-Temperature/validator/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ESP32 Status",
  "type": "object",
  "required": [
    "status",
    "location",
    "regul",
    "info",
    "net",
    "reporthost"
  ],
  "additionalProperties": false,
  "properties": {
    "status": {
      "type": "object",
      "required": [
        "temperature",
        "light",
        "regul",
        "fire",
        "heat",
        "cold",
        "fanspeed"
      ],
      "additionalProperties": false,
      "properties": {
        "temperature": {"type": "number"},
        "light": {"type": "integer", "minimum": 0},
        "regul": {"type": "string", "enum": ["RUNNING", "HALT"]},
        "fire": {"type": "boolean"},
        "heat": {"type": "string", "enum": ["ON", "OFF"]},
        "cold": {"type": "string", "enum": ["ON", "OFF"]},
        "fanspeed": {"type": "integer", "minimum": 0}
      }
    },
    "location": {
      "type": "object",
      "required": ["room", "gps", "address"],
      "additionalProperties": false,
      "properties": {
        "room": {"type": "string"},
        "gps": {
          "type": "object",
          "required": ["lat", "lon"],
          "additionalProperties": false,
          "properties": {
            "lat": {"type": "number", "minimum": -90, "maximum": 90},
            "lon": {"type": "number", "minimum": -180, "maximum": 180}
          }
        },
        "address": {"type": "string"}
      }
    },
    "regul": {
      "type": "object",
      "required": ["lt", "ht"],
      "additionalProperties": false,
      "properties": {
        "lt": {"type": "number"},
        "ht": {"type": "number"}
      }
    },
    "info": {
      "type": "object",
      "required": ["ident", "user", "loc"],
      "additionalProperties": false,
      "properties": {
        "ident": {"type": "string"},
        "user": {"type": "string"},
        "loc": {"type": "string"}
      }
    },
    "net": {
      "type": "object",
      "required": ["uptime", "ssid", "mac", "ip"],
      "additionalProperties": false,
      "properties": {
        "uptime": {"type": "string"},
        "ssid": {"type": "string"},
        "mac": {"type": "string"},
        "ip": {"type": "string"}
      }
    },
    "reporthost": {
      "type": "object",
      "required": ["target_ip", "target_port", "sp"],
      "additionalProperties": false,
      "properties": {
        "target_ip": {"type": "string"},
        "target_port": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "sp": {"type": "integer"}
      }
    }
  }
}

=== BeignetBoyy/IOT-Regulateur-Temperature/validator/esp.json
{
  "status": {
    "temperature": 25.9375,
    "light": 123,
    "regul": "HALT",
    "fire": true,
    "heat": "OFF",
    "cold": "OFF",
    "fanspeed": 1234
  },
  "location": {
    "room": "312",
    "gps": {
      "lat": 43.62453842,
      "lon": 7.050628185
    },
    "address": "Les lucioles"
  },
  "regul": {
    "lt": 26,
    "ht": 25.9
  },
  "info": {
    "ident": "ESP32 123",
    "user": "GM",
    "loc": "A Biot"
  },
  "net": {
    "uptime": "55",
    "ssid": "Livebox-B870",
    "mac": "AC:67:B2:37:C9:48",
    "ip": "192.168.1.45"
  },
  "reporthost": {
    "target_ip": "127.0.0.1",
    "target_port": 1880,
    "sp": 2
  }
}
